export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGGING_IN = 'USER_LOGGING_IN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const PRODUCTS_UPDATED = 'PRODUCTS_UPDATED'
export const ARTICLES_UPDATED = 'ARTICLES_UPDATED'
export const SALES_UPDATED = 'SALES_UPDATED'
export const CAMPAIGN_IMAGES_UPDATED = 'CAMPAIGN_IMAGES_UPDATE'
export const SHOPS_UPDATED = 'SHOPS_UPDATED'

export const CHANGE_TAB = 'CHANGE_TAB'